services:
  - type: web
    name: smartai-backend
    env: docker
    repo: https://github.com/gridllc/smartai-backend
    branch: main
    plan: starter
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1-aws
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false