services:
  - type: web
    name: smartai-backend
    env: docker
    repo: https://github.com/gridllc/smartai-backend
    branch: main
    plan: starter
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-east-1-aws
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ACTIVITY_LOG_PATH
        sync: false
      - key: ADMIN_EMAILS
        sync: false
      - key: DB_PATH
        sync: false
      - key: STATIC_DIR
        sync: false
      - key: TRANSCRIPT_DIR
        sync: false
      - key: UPLOAD_DIR
        sync: false
      - key: MAX_FILE_SIZE
        sync: false